[server]
port=9090
thread_count=4

[database]
path=./data/livekit.db

[recording]
path=./static/recordings
ffmpeg_path=/usr/bin/ffmpeg

[nginx]
rtmp_host=127.0.0.1
rtmp_port=1935

[log]
level=info
path=./logs/livekit.log
