[server]
port=9090
thread_count=4
host=192.168.124.129

[database]
path=./data/livekit.db

[recording]
path=./static/recordings
ffmpeg_path=/usr/bin/ffmpeg

[nginx]
rtmp_host=192.168.124.129
rtmp_port=1935
server_ip=192.168.124.129

[log]
level=debug
path=./logs/livekit.log
